### ISSUE TITLE
Notice crash admin menu and GUI buttons

### ISSUE THREAD

**Issue by selindmarkl** [Yoast/google-analytics-for-wordpress#277] opened 2015-01-10 09:38 UTC
WP: 4.1
Analytics: Version 5.2.8

After latest update of plugin an notice about cookies appears.

http://kiube.se
Notice: Use of undefined constant AUTH_COOKIE - assumed 'AUTH_COOKIE' in /hsphere/local/home/jidoka/kiube.se/wp-includes/pluggable.php on line 788 Notice: Use of undefined constant LOGGED_IN_COOKIE - assumed 'LOGGED_IN_COOKIE' in /hsphere/local/home/jidoka/kiube.se/wp-includes/user.php on line 242

**Comment by xDiglett** [comment] 2015-01-14 11:54
Please fix this, admin menu won't appear.

**Comment by andrebalza** [comment] 2015-01-14 15:18
same notice as above, if wp_debug enabled. front-end topbar menu does not appear. 
using wp 4.1 in multisite
yoast analytics 5.2.8

**Comment by tacoverdo** [comment] 2015-01-14 15:34
Duplicate of #271

**Closed by tacoverdo** 2015-01-14 15:34 UTC
