### ISSUE TITLE
Backend of site random - Fatal error: Internal Zend error

### ISSUE THREAD

**Issue by laserjobs** [Yoast/google-analytics-for-wordpress#216] opened 2014-12-11 21:03 UTC
Started with the Version 5.2.3 I sometimes get the following message working in the backend of the site
Fatal error: Internal Zend error - Missing class information for in /home/content/98/7381098/html/fmi/godairyfree/wp-content/plugins/google-analytics-for-wordpress/admin/api-libs/oauth/class-api-oauth.php on line 5

**Comment by sstiavetti** [comment] 2015-01-06 02:56
Getting a PHP Fatal Error on the free Google Analytics plugin. Running on Synthesis, most recent version of Wordpress. The plugin also continually loses its connection to Analytics and needs to be reconnected.

```2015-01-03 18:28:25.000 UTC
PHP Fatal error: Internal Zend error - Missing class information for in /var/www/theculinarylife.com/wp-content/plugins/google-analytics-for-wordpress/admin/api-libs/googleanalytics/class-api-googleanalytics.php on line 5
2015-01-03 18:28:21.000 UTC
PHP Fatal error: Internal Zend error - Missing class information for in /var/www/theculinarylife.com/wp-content/plugins/google-analytics-for-wordpress/admin/api-libs/googleanalytics/class-api-googleanalytics.php on line 5
2015-01-03 18:28:06.000 UTC
PHP Fatal error: Internal Zend error - Missing class information for in /var/www/theculinarylife.com/wp-content/plugins/google-analytics-for-wordpress/admin/api-libs/googleanalytics/class-api-googleanalytics.php on line 5
2015-01-03 18:28:02.000 UTC
PHP Fatal error: Internal Zend error - Missing class information for in /var/www/theculinarylife.com/wp-content/plugins/google-analytics-for-wordpress/admin/api-libs/googleanalytics/class-api-googleanalytics.php on line 5
2015-01-03 18:28:00.000 UTC
PHP Fatal error: Internal Zend error - Missing class information for in /var/www/theculinarylife.com/wp-content/plugins/google-analytics-for-wordpress/admin/api-libs/googleanalytics/class-api-googleanalytics.php on line 5
```

**Comment by laserjobs** [comment] 2015-01-06 03:41
sstiavetti what version of PHP are you running and is APC enabled?

**Comment by sstiavetti** [comment] 2015-01-07 11:37
The PHP version running on the server is 5.3.10 and yes APC is enabled.

**Comment by laserjobs** [comment] 2015-01-07 15:16
Until it is fixed you need to disable APC

**Comment by tacoverdo** [comment] 2015-01-07 15:59
@sstiavetti & @laserjobs: The alternative work around seems to be updating to a current version of PHP (5.4, 5.5 or 5.6).

**Comment by laserjobs** [comment] 2015-01-07 16:25
Does it work on PHP 5.4 with APC (still an option on PHP 5.4) as tends to kick out 500 errors instead of line errors in PHP 5.3 when the process is restarted?

**Comment by omarreiss** [comment] 2015-01-12 12:43
We think the bug was caused by the inclusion checks we wrapped around all of our classes. This was fixed in #282. I'll add a beta zip here shortly.

**Comment by webmozart** [comment] 2015-01-14 15:07
I'm experiencing this bug too.

**Comment by tacoverdo** [comment] 2015-01-19 08:41
You can find the beta in [this topic on yoast.com](https://yoast.com/public-betas-plugins/).

**Comment by laserjobs** [comment] 2015-01-28 15:38
Not seeing any errors with APC enabled with released Version 5.3

**Comment by Rarst** [comment] 2015-02-03 19:13
There seems to be PR open for it at the libs repo https://github.com/Yoast/api-libs/pull/17

**Closed** 2015-02-09 16:19 UTC
Labels: bug, pivotal

**Comment by jasonhendriks** [comment] 2015-06-20 15:56
Once of my user just brought this to my attention as well, for my own plugin Postman SMTP

> "Until it is fixed you need to disable APC"

That just feels wrong, doesn't it? Like throwing the baby out with the bathwater.

> "We think the bug was caused by the inclusion checks we wrapped around all of our classes"

This was a huge help in finding the error in my own code, as was this link @laserjobs posted, because of the article it linked to : http://notmysock.org/blog/php/inclusion-checks

Turns out I erroneously had a `require` that should have been `require_once`. No need to remove the conditional class wrappers.

**Comment by prionkor** [comment] 2015-12-10 05:21
@jasonhendriks I have just got similar report from one of my plugin user. BTW, in my case the class was included with `require_once`. They user is on shared hosting so I don't think APC can be disabled if enabled. 

The error is very random. It something get thrown sometime does not. One thing though the class is added with `class_exists()` check. Probably I should remove it on next version.
