### ISSUE TITLE
Redirected to empty page when clicking re-authenticate link

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/google-analytics-for-wordpress#372] opened 2015-04-20 15:46 UTC
After updating to 5.4 I see the following notice on the Dashboard-screen. When clicking the link to re-authenticate, I'm redirected to an empty settings page.

*Notice*
![yoast_google_analytics__dashboard_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/7234069/e1610e48-e784-11e4-9993-4662c8f31f22.png)

*Result*
![yoast_google_analytics__settings_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/7234105/172b2428-e785-11e4-86a9-ee214b116303.png)

**Comment by CarolineGeven** [comment] 2015-10-01 10:26
I can't reproduce this bug. I'm redirected to the settings page without problem. Closing this for now.

**Closed by CarolineGeven** 2015-10-01 10:26 UTC
Labels: bug, scheduled
